version: '3'

services:
  react-app:
    build:
      context: ./front-react
    ports:
      - "3000:3000"
    volumes:
      - ./front-react/:/usr/src/app/react/

  back:
    build:
      context: ./back
    ports:
      -"4000:4000"
    volumes:
      -./back/:/usr/src/app/back/
